config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :products
  resources :warehouses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :warehouse_products
  has_many :warehouses, through: :warehouse_products

  validates :name, presence: true
  validates :UPC, presence: true
  validates_uniqueness_of :UPC
  validates :quantity, presence: true
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :warehouse_products
  has_many :products, through: :warehouse_products

  validates :name, presence: true
  validates :address_1, presence: true
  validates :city, presence: true
  validates :state_province, presence: true
  validates :zip_postal, presence: true
  validates :country, presence: true

  def country_name
    country = ISO3166::Country[self.country]
    country.translations[I18n.locale.to_s] || country.iso_short_name
  end
end

app/models/warehouse_product.rb
class WarehouseProduct < ApplicationRecord
  belongs_to :product
  belongs_to :warehouse
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    product_params[:warehouse_ids].each do |w|
      @product.warehouses << Warehouse.find(w) if w.present?
    end

    if @product.save
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    product_params[:warehouse_ids].each do |w|
      @product.warehouses << Warehouse.find(w) if w.present?
    end

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy

    redirect_to products_path, status: :see_other
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params
      .require(:product)
      .permit(:name, :UPC, :quantity, :description, warehouse_ids: [])
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[show edit update destroy]

  def index
    @warehouses = Warehouse.all
  end

  def show; end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      redirect_to @warehouse
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to @warehouse
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @warehouse.destroy

    redirect_to warehouses_path, status: :see_other
  end

  private

  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  def warehouse_params
    params
      .require(:warehouse)
      .permit(
        :name,
        :address_1,
        :address_2,
        :city,
        :state_province,
        :zip_postal,
        :country,
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/dashboard/index.html.erb
<%- title "Dashboard" %>
<p>Welcome to the Inventory Tracker dashboard.</p>
<div class="row py-2">
  <h4 class="my-3">Recent Products</h4>
  <% if Product.count > 0 %> <% Product.order("id desc")[0...3].each do |p| %>
      <div class="col-sm-4">
        <div class="card text-center bg-light border-0">
          <p class="card-header show-label p-3 border-0"><%= p.name %></p>
          <div class="card-body">
            <p class="card-text">UPC: <%= p.UPC %></p>
            <p class="card-text">QTY: <%= p.quantity %></p>
            <%= link_to "View", p, class:"btn btn-secondary btn-sm" %>
          </div>
        </div>
      </div>
    <% end %> <% else %> There are no products in the database. <% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-auto ms-auto">
      <%= link_to products_url, class:"text-decoration-none" do %> View all
        products <%= render(Primer::OcticonComponent.new(:"arrow-right")) %> <%
      end %>
      </div>
    </div>
  </div>
  <div class="row py-2">
    <h4 class="my-3">Recent Warehouses</h4>
    <% if Warehouse.count > 0 %> <% Warehouse.order("id desc")[0...3].each do |w|
  %>
      <div class="col-sm-4">
        <div class="card text-center bg-light border-0">
          <p class="card-header show-label p-3 border-0"><%= w.name %></p>
          <div class="card-body">
            <p class="card-text"><%= w.address_1 %></p>
            <p class="card-text"><%= w.country_name %></p>
            <%= link_to "View", w, class:"btn btn-secondary btn-sm" %>
          </div>
        </div>
      </div>
    <% end %> <% else %> There are no warehouses in the database. <% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-auto ms-auto">
      <%= link_to warehouses_url, class:"text-decoration-none" do %> View all
        warehouses <%= render(Primer::OcticonComponent.new(:"arrow-right")) %> <%
      end %>
      </div>
    </div>
  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-vertical navbar-light bg-light">
  <div class="navbar-header mt-4"><%= image_tag("logo.png") %></div>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to :root, class:"nav-link" do %> <%= image_tag("home.svg") %>
        Dashboard <% end %>
    </li>
    <li class="nav-item">
      <%= link_to products_url, class:"nav-link" do %> <%=
      image_tag("products.svg") %> Products <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_product_url, class:"nav-link" do %> <%=
      image_tag("add.svg") %> Add Product <% end %>
    </li>
    <li class="nav-item">
      <%= link_to warehouses_url, class:"nav-link" do %> <%=
      image_tag("warehouse.svg") %> Warehouses <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_warehouse_url, class:"nav-link" do %> <%=
      image_tag("add.svg") %> Add Warehouse <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? "Inventory Tracker | #{content_for(:title)}" : "Inventory Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="wrapper">
      <%= render "layouts/navigation" %>
      <div class="main-content">
        <div class="header container">
          <div class="row h-100">
            <div class="col my-auto">
              <h1 class="h5 mb-0 mt-2 text-primary">Inventory Tracker</h1>
            </div>
          </div>
        </div>
        <hr class="my-3" />
        <div class="container pb-5 px-4">
          <div class="row">
            <div class="col-12">
              <h1 class="text-secondary h2"><%= content_for?(:title) ? content_for(:title) : "Inventory Tracker" %></h1>
            </div>
          </div>
          <%= yield %>
        </div>
      </div>
    </body>
  </html>

app/views/products/_form.html.erb
<div class="form-container bg-light rounded p-4">
  <%= form_with model: product, html: {class: "row g-3"} do |form| %>
    <div class="col-sm-12">
      <div class="form-floating">
        <%= form.text_field :name, {class:"form-control", id:"p_name"} %>
        <%= form.label :name, {class:"form-label", for:"p_name"} %>
      </div>
      <% @product.errors.full_messages_for(:name).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-6">
      <div class="form-floating">
        <%= form.text_field :UPC, {class:"form-control", id:"p_upc"} %>
        <%= form.label :UPC, "UPC", {class:"form-label", for:"p_upc"} %>
      </div>
      <% @product.errors.full_messages_for(:UPC).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-6">
      <div class="form-floating">
        <%= form.number_field :quantity, {class:"form-control", id:"p_quantity"} %>
        <%= form.label :quantity, {class:"form-label", for:"p_quantity"} %>
      </div>
      <% @product.errors.full_messages_for(:quantity).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-12">
      <div class="form-floating">
        <%= form.text_area :description, {class:"form-control", id:"p_description", rows:"3"} %>
        <%= form.label :description, {class:"form-label", for:"p_description"} %>
      </div>
    </div>
    <div class="accordion col-sm-12" id="warehouses-accordion">
      <div class="accordion-item">
        <button class="ps-0 accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#warehouses-collapse" aria-expanded="false" aria-controls="warehouses-collapse">
          <span class="accordion-label">Warehouse(s)</span>
        </button>
        <div id="warehouses-collapse" class="accordion-collapse collapse" data-bs-parent="#warehouses-accordion">
          <div class="accordion-body">
            <div class="form-check">
              <%= form.collection_check_boxes(:warehouse_ids, Warehouse.order(:name), :id, :name) do |b| %>
                <%= b.label class:"form-check-label" do %>
                  <%= b.check_box(class:"form-check-input") + b.text %>
                <% end %> <br>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-auto ms-auto">
      <%= form.submit class:"btn btn-primary text-white" %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<%- title "Edit Product" %>
<%= render "form", product: @product %>

app/views/products/index.html.erb
<%- title "Products" %>
<div class="card border-light">
  <div class="table-responsive">
    <table class="table align-middle mb-0  table-borderless">
      <thead class="table-light">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">UPC</th>
          <th scope="col">Quantity</th>
          <th scope="col">Warehouses</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="border-light">
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= link_to product.name, product %></td>
            <td><%= product.UPC %></td>
            <td><%= product.quantity %></td>
            <td><% product.warehouses[0...3].each do |w| %>
                <%= link_to w.name, w, class:"badge bg-secondary rounded-pill text-decoration-none" %>
              <% end %>
              <% if product.warehouses.count > 3 %>
                <span class="badge bg-primary rounded-pill">+ <%= product.warehouses.count - 3  %></span>
              <% end %>
            </td>
            <td><%= link_to render(Primer::OcticonComponent.new(:"pencil")), edit_product_path(product) %> <%= link_to render(Primer::OcticonComponent.new(:"x")), product_path(product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete this item?"
                } %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/new.html.erb
<%- title "New Product" %>
<%= render "form", product: @product %>

app/views/products/show.html.erb
<%- title @product.name  %>
<div class="container bg-light rounded p-4">
  <div class="row">
    <div class="d-flex justify-content-between px-3 align-items-center pb-3">
      <div class="d-flex justify-content-start align-items-center">
        <span class="show-label me-1">UPC:</span> <%= @product.UPC %>
      </div>
      <div class="d-flex justify-content-end"> <span class="product-label">ID:</span><span class="badge rounded-pill bg-dark mx-2"> <%= @product.id %> </span> </div>
    </div>
    <div class="px-3">
      <span class="show-label me-1">Warehouses:</span>
      <% if @product.warehouses.present? %>
        <% @product.warehouses.each do |w| %>
          <%= link_to w.name, w, class:"badge bg-primary rounded-pill text-decoration-none" %>
        <% end %>
      <% else %>
        <div class="alert alert-dark d-flex align-items-center py-2 my-1" role="alert">
          <%= render(Primer::OcticonComponent.new(:"info")) %>
          <div class="ms-3">
            This product does not belong to any warehouses.
          </div>
        </div>
      <% end %>
      <div class="card my-3">
        <div class="card-header bg-dark">
          <span class="show-label text-white">Description</span>
        </div>
        <div class="card-body">
          <p class="card-text"><%= @product.description.present? ? @product.description : "No description available." %></p>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-end px-3 pt-1">
      <span class="badge bg-white mx-2 p-3 rounded-pill"><%= link_to render(Primer::OcticonComponent.new(:"pencil")), edit_product_path(@product) %></span>
      <span class="badge bg-white mx-2 p-3 rounded-pill"><%= link_to render(Primer::OcticonComponent.new(:"trash")), product_path(@product), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure you want to delete this item?"
            } %></span>
    </div>
  </div>
</div>

app/views/warehouses/_form.html.erb
<div class="form-container bg-light rounded p-4">
  <%= form_with model: warehouse, html: {class: "row g-3"} do |form| %>
    <div class="col-sm-12">
      <div class="form-floating">
        <%= form.text_field :name, {class:"form-control", id:"w_name"} %>
        <%= form.label :name, {class:"form-label", for:"w_name"} %>
      </div>
      <% @warehouse.errors.full_messages_for(:name).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-12">
      <div class="form-floating">
        <%= form.text_field :address_1, {class:"form-control", id:"w_addr"} %>
        <%= form.label :address_1, "Street address", {class:"form-label", for:"w_addr"} %>
      </div>
      <% @warehouse.errors.full_messages_for(:address_1).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-12">
      <div class="form-floating">
        <%= form.text_field :address_2, {class:"form-control", id:"w_addr2"} %>
        <%= form.label :address_2, "Street address 2", {class:"form-label", for:"w_addr2"} %>
      </div>
      <% @warehouse.errors.full_messages_for(:address_2).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-6">
      <div class="form-floating">
        <%= form.country_select :country, { include_blank: true }, { class:"form-select", id:"w_country"} %>
        <%= form.label :country, {class:"form-label", for:"w_country"} %>
      </div>
      <% @warehouse.errors.full_messages_for(:country).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-6">
      <div class="form-floating">
        <%= form.text_field :city, {class:"form-control", id:"w_city"} %>
        <%= form.label :city, {class:"form-label", for:"w_city"} %>
      </div>
      <% @warehouse.errors.full_messages_for(:city).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-6">
      <div class="form-floating">
        <%= form.text_field :state_province, {class:"form-control", id:"w_state"} %>
        <%= form.label :state_province, "State / Province", {class:"form-label", for:"w_state"} %>
      </div>
      <% @warehouse.errors.full_messages_for(:state_province).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-sm-6">
      <div class="form-floating">
        <%= form.text_field :zip_postal, {class:"form-control", id:"w_zip"} %>
        <%= form.label :zip_postal, "ZIP / Postal Code", {class:"form-label", for:"w_zip"} %>
      </div>
      <% @warehouse.errors.full_messages_for(:zip_postal).each do |message| %>
        <div class="p-2 text-danger"><%= message %></div>
      <% end %>
    </div>
    <div class="col-auto ms-auto">
      <%= form.submit class:"btn btn-primary text-white" %>
    </div>
  <% end %>
</div>

app/views/warehouses/edit.html.erb
<%- title "Edit Warehouse" %>
<%= render "form", warehouse: @warehouse %>

app/views/warehouses/index.html.erb
<%- title "Warehouses" %>
<div class="card border-light">
  <div class="table-responsive">
    <table class="table align-middle mb-0  table-borderless">
      <thead class="table-light text-secondary">
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Street Address</th>
          <th scope="col">Country</th>
          <th scope="col">City</th>
          <th scope="col">State / Province</th>
          <th scope="col">ZIP / Postal Code</th>
          <th scope="col">No. Products</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody class="border-light">
        <% @warehouses.each do |warehouse| %>
          <tr>
            <td><%= warehouse.id %></td>
            <td><%= link_to warehouse.name, warehouse %></td>
            <td><%= warehouse.address_1 %>
              <% warehouse.address_2.present? do %>
                <%= warehouse.address_2 %>
              <% end %>
            </td>
            <td><%= warehouse.country %></td>
            <td><%= warehouse.city %></td>
            <td><%= warehouse.state_province %></td>
            <td><%= warehouse.zip_postal %></td>
            <td><span class="badge bg-primary rounded-pill"> <%= warehouse.products.count %></span></td>
            <td><%= link_to render(Primer::OcticonComponent.new(:"pencil")), edit_warehouse_path(warehouse) %> <%= link_to render(Primer::OcticonComponent.new(:"x")), warehouse_path(warehouse), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to delete this item?"
                } %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/warehouses/new.html.erb
<%- title "New Warehouse" %>
<%= render "form", warehouse: @warehouse %>

app/views/warehouses/show.html.erb
<%- title @warehouse.name %>
<div class="container bg-light rounded p-4">
  <div class="row">
    <div class="d-flex justify-content-between px-3 align-items-top">
      <div class="d-flex justify-content-start align-items-top">
        <span class="show-label me-1">Address:</span>
      </div>
      <div class="d-flex justify-content-end"> <span class="show-label">ID:</span><span class="badge rounded-pill bg-dark mx-2"> <%= @warehouse.id %> </span> </div>
    </div>
    <div class="px-3">
      <%= @warehouse.address_1 %> <br>
      <% @warehouse.address_2.present? do %>
        <%= warehouse.address_2 %><br>
      <% end %>
      <%= @warehouse.city %>, <%= @warehouse.state_province %> <%= @warehouse.zip_postal %> <br>
      <%= @warehouse.country_name %> <br>
    </div>
    <div class="d-flex justify-content-end px-3 pt-1">
      <span class="badge bg-white mx-2 p-3 rounded-pill"><%= link_to render(Primer::OcticonComponent.new(:"pencil")), edit_warehouse_path(@warehouse) %></span>
      <span class="badge bg-white mx-2 p-3 rounded-pill"><%= link_to render(Primer::OcticonComponent.new(:"trash")), warehouse_path(@warehouse), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure you want to delete this item?"
            } %></span>
    </div>
  </div>
</div>
<div class="row my-4">
  <div class="col">
    <h5 class="text-secondary">Products at this warehouse</h3>
    <% if @warehouse.products.present? %>
      <div class="card border-light">
        <div class="table-responsive">
          <table class="table align-middle mb-0  table-borderless">
            <thead class="table-light">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">UPC</th>
                <th scope="col">Quantity</th>
              </tr>
            </thead>
            <tbody class="border-light">
              <% @warehouse.products.each do |product| %>
                <tr>
                  <td><%= product.id %></td>
                  <td><%= link_to product.name, product %></td>
                  <td><%= product.UPC %></td>
                  <td><%= product.quantity %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% else %>
      <div class="alert alert-dark d-flex align-items-center py-2 my-1" role="alert">
        <%= render(Primer::OcticonComponent.new(:"info")) %>
        <div class="ms-3">
          This warehouse does not contain any products.
        </div>
      </div>
    <% end %>
  </div>
</div>